# Generated by Django 5.0.6 on 2024-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authormodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
